name: lingualeap_app
description: "LinguaLeap - English Learning App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP & GraphQL
  dio: ^5.4.3+1
  graphql_flutter: ^5.2.0-beta.6
  http: ^1.1.0  # ← NEW: HTTP client for speech recognition APIs
  flutter_dotenv: ^5.1.0  # ← NEW: Environment variables support
  
  # State Management
  provider: ^6.1.2
  get: ^4.6.6  # ← NEW: GetX for vocabulary management
  
  # Storage
  shared_preferences: ^2.2.3
  
  # Audio & Firebase
  audioplayers: ^5.2.1
  firebase_core: ^2.32.0
  permission_handler: ^11.1.0
  universal_io: ^2.2.2
  record: ^4.4.4

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

 


flutter:
  uses-material-design: true
  assets:
    - assets/banner/banner-vip.jpg 
