// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHQ3R4VeiN5PVmu3Y0yjrMB4AVgyd11r0',
    appId: '1:468247867417:web:d2efeb3b1a87c0e0707a88',
    messagingSenderId: '468247867417',
    projectId: 'lingualeap-ed012',
    authDomain: 'lingualeap-ed012.firebaseapp.com',
    storageBucket: 'lingualeap-ed012.firebasestorage.app',
    measurementId: 'G-LKJF51GCEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARSQ09PhWm6ee1W74PFBdUqR-XMMevscI',
    appId: '1:468247867417:android:93a6f7d23243ea4e707a88',
    messagingSenderId: '468247867417',
    projectId: 'lingualeap-ed012',
    storageBucket: 'lingualeap-ed012.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0bOxpBR14BOaHeaJGCzb0IU_efdtpcRQ',
    appId: '1:468247867417:ios:5d34af06cd7f55ad707a88',
    messagingSenderId: '468247867417',
    projectId: 'lingualeap-ed012',
    storageBucket: 'lingualeap-ed012.firebasestorage.app',
    iosBundleId: 'com.example.lingualeapApp',
  );

}